import '@mantine/core/styles.css';

import type { Metadata } from 'next';
import { MantineProvider } from '@mantine/core';
import { GoogleAnalytics } from '@next/third-parties/google';
import { Toaster } from 'react-hot-toast';

import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID} />
        <MantineProvider>{children}</MantineProvider>
        <Toaster
          toastOptions={{
            style: {
              background: '#fff',
              color: '#000',
              fontSize: '0.85rem',
              padding: '8px 16px',
              fontWeight: 500,
            },
            duration: 3000,
            position: 'top-right',
          }}
        />
      </body>
    </html>
  );
}
