import '@mantine/core/styles.css';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { MantineProvider } from '@mantine/core';
import { GoogleAnalytics } from '@next/third-parties/google';
import { Toaster } from 'react-hot-toast';

import './globals.css';

const fontSans = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${fontSans.className} font-sans `}>
        <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID} />
        <MantineProvider>{children}</MantineProvider>
        <Toaster
          toastOptions={{
            style: {
              background: '#fff',
              color: '#444',
              fontSize: '0.85rem',
              padding: '8px 16px',
              fontWeight: 500,
            },
            duration: 3000,
            position: 'top-right',
          }}
        />
      </body>
    </html>
  );
}
