import type { Metadata } from 'next';
import '../../app/globals.css';
import LayoutWrapper from '../common/section/dashboard/layout-wrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return <LayoutWrapper>{children}</LayoutWrapper>;
}
