import type { Metadata } from 'next';
import '../../app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <main className="min-h-screen bg-linear-to-br from-amber-50 via-amber-50 to-orange-50 flex items-center justify-center p-4">
      {children}
    </main>
  );
}
